name: Build Solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: "Relocation Section Editor.sln"
      Configuration: ${{ matrix.configuration }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore the application
      run: dotnet restore $env:Solution_Name
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Build the solution
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore

    - name: Publish the application
      run: dotnet publish $env:Solution_Name --configuration $env:Configuration --output publish_output
